const QuestionsActionTypes = {
  FETCH_QUESTIONS_START: "FETCH_QUESTIONS_START",
  FETCH_QUESTIONS_SUCCESS: "FETCH_QUESTIONS_SUCCESS",
  FETCH_QUESTIONS_FAILURE: "FETCH_QUESTIONS_FAILURE",
  ADD_NEW_QUESTION_START: "ADD_NEW_QUESTION_START",
  ADD_NEW_QUESTION_SUCCESS: "ADD_NEW_QUESTION_SUCCESS",
  ADD_NEW_QUESTION_FAILURE: "ADD_NEW_QUESTION_FAILURE",
  SAVE_QUESTION_ANSWER_START: "SAVE_QUESTION_ANSWER_START",
  SAVE_QUESTION_ANSWER_SUCCESS: "SAVE_QUESTION_ANSWER_SUCCESS",
  SAVE_QUESTION_ANSWER_FAILURE: "SAVE_QUESTION_ANSWER_FAILURE",
};

export default QuestionsActionTypes;
