const UsersActionTypes = {
  FETCH_USERS_START: "FETCH_USERS_START",
  FETCH_USERS_SUCCESS: "FETCH_USERS_SUCCESS",
  FETCH_USERS_FAILURE: "FETCH_USERS_FAILURE",
  SET_AUTHED_USER: "SET_AUTHED_USER",
  DELETE_AUTHED_USER: "DELETE_AUTHED_USER",
};

export default UsersActionTypes;
